### ISSUE TITLE
Not respecting "pretter" config's 

### ISSUE THREAD

**Issue by HymanZHAN** [dprint/dprint-plugin-prettier#4]
## My `dprintrc.json`

```json
{
  "$schema": "https://dprint.dev/schemas/v0.json",
  "projectType": "educational",
  "prettier": {
    "trailingComma": "es5",
    "tabWidth": 2,
    "semi": true,
    "printWidth": 100,
    "bracketSpacing": true,
    "arrowParens": "always"
  },
  "incremental": true,
  "includes": ["**/*.{.vue,ts,js}"],
  "excludes": ["**/node_modules", "**/*-lock.json"],
  "plugins": [
    "https://plugins.dprint.dev/prettier-0.2.1.exe-plugin@c051918d0c4cf082b5ccdf92e89af3dcb2859e18f75073ba16dda6366e493a03"
  ]
}
```

## Problem

`drpint` command is not respecting my `"prettier"` section of the config file. Am I missing something?

**Comment by dsherret** [comment]
Yeah, there are some bugs here. You can see how it's behaving by looking at `dprint output-resolved-config`. I will submit some fixes and do a new release soon.

**Comment by HymanZHAN** [comment]
Got it. That's a nifty command! Guess I will need to go through the doc more carefully.
Thanks for the quick fix! Really appreciate it.

**Comment by dsherret** [comment]
@HymanZHAN yeah, it's very useful for debugging purposes. There is also `dprint output-file-paths` and `dprint output-format-times` too.

I really need automated tests on this repo. It's one of the only ones without tests and sorry you've run into all these issues :(

At least the fix is now available. It seems to work for me now: https://github.com/dprint/dprint-plugin-prettier/releases/
